project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!diapos/"
  resources:
    - "files/"
    - "diapos/*.html"
    - "diapos/*.pdf"
    - "diapos/img/"
    - "diapos/fig/"
    - "diapos/libs/"
    - "diapos/partials/"
    - "diapos/*_files/"

bibliography: files/bib/math60604.bib
csl: files/bib/apa.csl

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes


toc-title: "Table des matières"
website:
  title: "Modélisation statistique"
  site-url: "https://lbelzile.github.io/modstat-a20"
  description: "Ce cours aborde notamment les modèles linéaires, les modèles linéaires généralisés et la régression pour données longitudinales avec effets aléatoires et structures de corrélation. Pour chacune de ces méthodes, les principes théoriques de l’inférence, tels que les tests d’hypothèse, statistiques de tests et méthodes d’estimation seront abordés avec rigueur. Une attention particulière sera aussi portée aux applications en gestion à l’aide du logiciel SAS."

  navbar:
    pinned: true
    background: "#002855"
    foreground: "#ffffff"
    right:
      - text: "Syllabus"
        file: "syllabus.qmd"
      - text: "Contenu"
        file: contenu/index.qmd
      - text: "Exercices"
        file: exercices/index.qmd
      - text: "Notes"
        href: "https://lbelzile.github.io/math60604"


  sidebar:
    - title: "Contenu"
      style: "docked"
      search: false
      foreground: "#002855"
      contents:
        - text: "Ressources"
          file: contenu/index.qmd
        - text: "Objectifs d'apprentissage"
          file:  "objectifsapprentissage.qmd"
        - text: "Installation de R"
          file: contenu/installation.qmd
        - section: "Contenu"
          contents:
            - text: "Semaine 1"
              file: contenu/01-contenu.qmd
            - text: "Semaine 2"
              file: contenu/02-contenu.qmd
            - text: "Semaine 3"
              file: contenu/03-contenu.qmd
            - text: "Semaine 4"
              file: contenu/04-contenu.qmd
            - text: "Semaine 5"
              file: contenu/05-contenu.qmd
            - text: "Semaine 6"
              file: contenu/06-contenu.qmd
    - title: "Exercices"
      style: "docked"
      search: false
      foreground: "#002855"
      contents:
        - text: "Exercises"
          file: exercices/index.qmd
        - section: "Inférence statistique"
          contents:
            - text: "Exercice 1"  
              file: exercices/01-exercice.qmd
            - text: "Solution 1"
              file: exercices/01-solution.qmd
        - section: "Activités en classe"
          contents:
            - text: "Tests d'hypothèse, modèles linéaires"
              file: exercices/modeles-lineaires-contrastes.qmd
            - text: "Interactions"
              file: exercices/interactions.qmd
            - text: "Diagnostics graphiques"
              file: exercices/diagnostics-graphiques.qmd 
  page-footer:
    left: |
      Contenu {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor1.name_no_title >}}]({{< var instructor1.url >}}), [{{< var instructor2.name_no_title >}}]({{< var instructor2.url >}})<br>; canevas du site par [Dr. Andrew Heiss](https://www.andrewheiss.com/) sous [licence MIT](https://mit-license.org/) <br>
      Tout le contenu du site (hors notes) est distribué sous licence {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Fabriqué avec {{< fa brands r-project >}} et [Quarto](https://quarto.org/)<br>
      [Code source sur {{< fa brands github >}} GitHub]({{< var course.github >}})

preview:
  port: 6200
  browser: true
  watch-inputs: true
  navigate: true

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
